### PR TITLE
Switch base to core22

### PR DESCRIPTION
**Pull request by nicolasbock**
Test builds are available at https://launchpad.net/~nicolasbock/+snap/hotsos-core22

Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>

### CODE REVIEW

**Comment by nicolasbock** [comment]
It looks like core22 changes something in terms of how libraries are treated. I am getting this error:

```console
$ ldd /snap/hotsos/current/usr/bin/python3.10
        linux-vdso.so.1 (0x00007fffe70b6000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3f6f865000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f3f6f83a000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f3f6f81e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3f6f600000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3f6ff40000)
```

Which looks very similar to the issues we had originally.

**Comment by nicolasbock** [comment]
`hotsos` is working on a sosreport. But on a live system it hangs and the last line printed is:
```
2022-11-15 15:48:41,935.935 10519 DEBUG None [-] YDefsContext setting import_cache={'hotsos.core.plugins.kubernetes.KubernetesChecksBase': <class 'hotsos.core.plugins.kubernetes.KubernetesChecksBase'>}
```

**Comment by nicolasbock** [comment]
The latest rebase works for me in a Focal and a Bionic VM.

**Comment by dosaboy** [comment]
i believe this is now fixed by https://github.com/canonical/hotsos/issues/464 so will close. Please reopen if i am mistaken.

**Pull request closed without merging**
