### PR TITLE
Add support for Pebble service manager

### PR DESCRIPTION
**Pull request by dosaboy**
Also extends CLIHelper to support trying more than one binary command. Note that pebble info is not yet supported in sosreport so this functionality is only available when running against a host.

Adapts openstack plugin to fallback to pebble if
systemd services not detected.

Resolves: #584

### CODE REVIEW

**Review by nicolasbock — CHANGES_REQUESTED** [review]
When I run this on a `nova-conductor` container, I get:

```yaml
openstack:
  release:
    name: yoga
    days-to-eol: 1463
  failed-parts:
    - agent_exceptions
  features:
    nova:
      main:
        debug: false
        live_migration_permit_auto_converge: false
        live_migration_permit_post_copy: false
    api-ssl: false
```
while on a `nova-cloud-conductor` VM:
```yaml
openstack:                                  
  release:                                   
    name: yoga                                
    days-to-eol: 1463                         
  services:                                                                                    
    systemd:                                                                                   
      enabled:                                                                                 
        - apache2                                                                              
        - haproxy
        - nova-cloud-controller-mysql-router
        - nova-conductor
        - nova-scheduler
      masked:
        - nova-api-os-compute
    ps:
      - apache2 (3)
      - haproxy (2)
      - nova-conductor (3)
      - nova-scheduler (3)
  features:               
    api-ssl: false
  agent-exceptions:                 
    nova:                      
      nova-scheduler:                         
        oslo_db.exception.DBNonExistentTable:
          '2023-04-27': 2                                                                      
```
The `pebbles` section is missing from the summary.

I am still investigating why...

**Comment by dosaboy** [comment]
> When I run this on a `nova-conductor` container, I get:
> 
> ```yaml
> openstack:
>   release:
>     name: yoga
>     days-to-eol: 1463
>   failed-parts:
>     - agent_exceptions
>   features:
>     nova:
>       main:
>         debug: false
>         live_migration_permit_auto_converge: false
>         live_migration_permit_post_copy: false
>     api-ssl: false
> ```
> 
> while on a `nova-cloud-conductor` VM:
> 
> ```yaml
> openstack:                                  
>   release:                                   
>     name: yoga                                
>     days-to-eol: 1463                         
>   services:                                                                                    
>     systemd:                                                                                   
>       enabled:                                                                                 
>         - apache2                                                                              
>         - haproxy
>         - nova-cloud-controller-mysql-router
>         - nova-conductor
>         - nova-scheduler
>       masked:
>         - nova-api-os-compute
>     ps:
>       - apache2 (3)
>       - haproxy (2)
>       - nova-conductor (3)
>       - nova-scheduler (3)
>   features:               
>     api-ssl: false
>   agent-exceptions:                 
>     nova:                      
>       nova-scheduler:                         
>         oslo_db.exception.DBNonExistentTable:
>           '2023-04-27': 2                                                                      
> ```
> 
> The `pebbles` section is missing from the summary.
> 
> I am still investigating why...

hmm ok ill try that out, another thing is that i realise i need to adapt the summary output to s/systemd/pebble/ when the services are in fact coming from pebble.

**Comment by dosaboy** [comment]
i've done a test with the latest code on a neutron-api unit and I get:

```
openstack:
  release:                  
    name: yoga                       
    days-to-eol: 1462
  services:             
    pebble:                                    
      active:    
        - neutron-server             
    ps:                    
      - neutron-server (1)
```

**Comment by nicolasbock** [comment]
This looks much better:
```yaml
openstack:                                                                                     
  release:                                                                                     
    name: yoga                                                                                 
    days-to-eol: 1457                                                                          
  services:
    pebble:
      active:
        - neutron-server
    ps:
      - neutron-server (1)
  dpkg:
    - keepalived 1:2.0.19-2ubuntu0.2
```

**Pull request merged**
