### PR TITLE
pylint: bump version to 3.1.0

### PR DESCRIPTION
**Pull request by mustafakemalgilor**
... to make it consistent with the `searchkit`. fixed the new warnings issued by the pylint.

### CODE REVIEW

**Review by brianphaley — APPROVED** [review]

**Review by brianphaley — APPROVED** [review]
Pon is fixing the resources.path issue in https://github.com/canonical/hotsos/pull/864

**Comment by mustafakemalgilor** [comment]
> Pon is fixing the resources.path issue in #864

actually I tried to fix that as well (#854) , but the thing is the alternative `resources.files` is missing in py3.8 so I didn't want to introduce two different code paths just to please the pylint. unfortunately it's not a drop-in replacement so we cannot do "import this if py3.8 else that" either. I guess we have to wait until we drop the py3.8 support.

**Review by pponnuvel — APPROVED** [review]
It makes sense to suppress it for now (until 3.8 support is dropped).

**Review by dosaboy — APPROVED** [review]
lgtm!

**Pull request merged**
