### PR TITLE
[kernel] Detect disk failure

### PR DESCRIPTION
**Pull request by nkshirsagar**
Resolves: #368

### CODE REVIEW

**Comment by nkshirsagar** [comment]
~~~
nikhil@nikhil-Lenovo-Legion-Y540-15IRH-PG0:~/HDD_MOUNT/Downloads/hotsos_fork/hotsos$ tox -epy3 tests.unit.test_kernel.TestKernelScenarioChecks.test_failing_disk
py3 installed: astroid==2.5.6,attrs==22.1.0,autopage==0.5.1,bashate==2.1.0,cffi==1.15.1,click==8.1.3,cliff==3.10.1,cmd2==2.4.2,cryptography==3.4.8,extras==1.0.0,fixtures==4.0.1,flake8==5.0.3,future==0.18.2,isort==5.10.1,lazy-object-proxy==1.7.1,mccabe==0.7.0,mock==4.0.3,pbr==5.9.0,prettytable==3.3.0,progress==1.6,pycodestyle==2.9.0,pycparser==2.21,pyflakes==2.5.0,pylint==2.8.3,pyparsing==3.0.9,pyperclip==1.8.2,python-subunit==1.4.0,PyYAML==6.0,rpdb==0.1.6,simplejson==3.17.6,stestr==3.2.1,stevedore==4.0.0,testtools==2.5.0,toml==0.10.2,voluptuous==0.13.1,wcwidth==0.2.5,wrapt==1.12.1
py3 run-test-pre: PYTHONHASHSEED='0'
py3 run-test: commands[0] | stestr run --serial --test-path /home/nikhil/HDD_MOUNT/Downloads/hotsos_fork/hotsos/tests/unit/ tests.unit.test_kernel.TestKernelScenarioChecks.test_failing_disk
{0} tests.unit.test_kernel.TestKernelScenarioChecks.test_failing_disk [0.016918s] ... ok

======
Totals
======
Ran: 1 tests in 0.0169 sec.
 - Passed: 1
 - Skipped: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 0
Sum of execute time for each test: 0.0169 sec.

==============
Worker Balance
==============
 - Worker 0 (1 tests) => 0:00:00.016918
~~~

**Review by nicolasbock — COMMENTED** [review]
Would it be possible to also print out which disk(s) is/are failing?

**Comment by nkshirsagar** [comment]
> Would it be possible to also print out which disk(s) is/are failing?

I will check on how to achieve this

**Comment by nkshirsagar** [comment]
> > Would it be possible to also print out which disk(s) is/are failing?
> 
> I will check on how to achieve this

done!

**Review by nicolasbock — APPROVED** [review]
Nice 😄

**Pull request merged**
