### PR TITLE
[core] Fix decode errors from searchkit

### LINKED ISSUE #860: searchkit doesn't handle unicode errors
```
2024-05-10 12:12:15,355 791905 ERROR searchkit [-] caught UnicodeDecodeError while searching ./var/log/kern.log
Traceback (most recent call last):
  File "/home/pponnuvel/.local/pipx/venvs/hotsos/lib/python3.8/site-packages/searchkit/search.py", line 1043, in execute
    fd.read(1)
  File "/usr/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'Ap')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pponnuvel/.local/pipx/venvs/hotsos/lib/python3.8/site-packages/searchkit/search.py", line 1048, in execute
    stats = self._run_search(fd)
  File "/home/pponnuvel/.local/pipx/venvs/hotsos/lib/python3.8/site-packages/searchkit/search.py", line 993, in _run_search
    line = line.decode("utf-8", **self.decode_kwargs)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 117: invalid continuation byte
2024-05-10 12:12:15,363 791878 DEBUG searchkit [-] joining/stopping queue consumer thread
2024-05-10 12:12:15,434 791878 DEBUG searchkit [-] exiting results thread
2024-05-10 12:12:15,434 791878 DEBUG searchkit [-] stopped fetching results (total received=0)
2024-05-10 12:12:15,434 791878 DEBUG searchkit [-] consumer thread stopped successfully
2024-05-10 12:12:15,437 791878 ERROR hotsos.plugin.lxd [-] part 'auto_scenario_check' raised exception: 'utf-8' codec can't decode byte 0xd2 in position 117: invalid continuation byte
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/pponnuvel/.local/pipx/venvs/hotsos/lib/python3.8/site-packages/searchkit/search.py", line 1043, in execute
    fd.read(1)
  File "/usr/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'Ap')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/pponnuvel/.local/pipx/venvs/hotsos/lib/python3.8/site-packages/searchkit/search.py", line 1048, in execute
    stats = self._run_search(fd)
  File "/home/pponnuvel/.local/pipx/venvs/hotsos/lib/python3.8/site-packages/searchkit/search.py", line 993, in 
      line = line.decode("utf-8", **self.decode_kwargs)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 117: invalid continuation byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pponnuvel/.local/pipx/venvs/hotsos/lib/python3.8/site-packages/hotsos/core/plugintools.py", line 402, in run
    always_parts().run()
  File "/home/pponnuvel/.local/pipx/venvs/hotsos/lib/python3.8/site-packages/hotsos/core/ycheck/scenarios.py", line 142, in run
    self.load()
  File "/home/pponnuvel/.local/pipx/venvs/hotsos/lib/python3.8/site-packages/hotsos/core/ycheck/scenarios.py", line 99, in load
    results = self.searcher.run()
  File "/home/pponnuvel/.local/pipx/venvs/hotsos/lib/python3.8/site-packages/searchkit/search.py", line 1446, in run
    self._run_mp(mgr, results, rs)
  File "/home/pponnuvel/.local/pipx/venvs/hotsos/lib/python3.8/site-packages/searchkit/search.py", line 1396, in _run_mp
    self.stats.update(future.result())
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 117: invalid continuation byte
```

`/customers/sncf/00382281/sosreport-ht202opp01-SNCF-00382281-2024-04-16-rmraxob.tar.xz` has the problematic `kern.log`.

### PR DESCRIPTION
**Pull request by pponnuvel**
When UTF-8 decoding fails, searchkit throws an exception.

Passing decode_errors='backslashreplace' to cope with that.

Fixes #860.

### CODE REVIEW

**Comment by mustafakemalgilor** [comment]
For the files that import FileSearcher from `hotsos.core.search`, i.e. ` from hotsos.core.search import (FileSearcher)`, we can pass DecodeError directly to the super().__init__:

https://github.com/canonical/hotsos/blob/4121edf5a5a9c964215e8bd35d471ac702612e89/hotsos/core/search.py#L24-L27

**Comment by pponnuvel** [comment]
> @pponnuvel For the files that import FileSearcher from `hotsos.core.search`, i.e. ` from hotsos.core.search import (FileSearcher)`, we can pass decode_errors directly to the `super().__init__` :
> 
> https://github.com/canonical/hotsos/blob/4121edf5a5a9c964215e8bd35d471ac702612e89/hotsos/core/search.py#L24-L27

Ah, I didn't realise there's another `FileSearcher` in hotsos itself! So that would simplify this change.  But is there any situation where we *do* want to see the decode errors and/or handle it? I don't envisage any - just wonder as this woud  prevent such things.

**Comment by pponnuvel** [comment]
@dosaboy https://github.com/pponnuvel/hotsos/commit/97b7d0505232edcec6320376f3caadb48dccfa1e is the other way. But I've a [question](https://github.com/canonical/hotsos/pull/861#issuecomment-2104598843).

**Comment by dosaboy** [comment]
I had had issues in the past when using decode error handlers since the injected characters can yield unexpected results from the constraints logic. Having said that I think with the current implementation is reasonably safe. I have however in recent times very seldom comes across this kind of error, would you be able to share anything about what file/output it was that failed? I wonder if a more selective approach would be better i.e. not doing this globally.

**Comment by pponnuvel** [comment]
@dosaboy 
Changing these two are for the specific sosreport I've issues with:
```
 hotsos/core/plugins/kernel/kernlog/common.py
 hotsos/core/plugins/lxd/common.py           
```

So we can limit to just to these two too.

`/customers/sncf/00382281/sosreport-ht202opp01-SNCF-00382281-2024-04-16-rmraxob.tar.xz` is the sosreport.

**Comment by dosaboy** [comment]
As a "safer" alternative what do you think about putting this behind a config option and making it optional e.g. --handle-utf8-decode-errors

**Comment by pponnuvel** [comment]
> As a "safer" alternative what do you think about putting this behind a config option and making it optional e.g. --handle-utf8-decode-errors. Overkill?

That's an option. But you need to know it first to ignore it. What you'd see is "failed-parts" in hotsos output which could be due to anything - not necessarily because "decode-errors".

Another question is what could be "unsafe" if we ignore it globally. Do we expect only UTF-8 and ignore anything else? or do we want to support multiple encodings?

It depends on what we *could* do when we hit decode errors . If the answer is "nothing as we only "grep" for ASCII text in all log/config files, so ignore it" then I'd prefer the global change (https://github.com/pponnuvel/hotsos/commit/97b7d0505232edcec6320376f3caadb48dccfa1e).

**Comment by pponnuvel** [comment]
@dosaboy Can we get this in? I hit this with every sosreport from a user...

**Comment by pponnuvel** [comment]
> Hi there @pponnuvel, @dosaboy! I'm confused about why this PR was closed. I've hit the same issue, this time on syslog. Pon's fix worked for me.

I tend to close "dormant" PRs - probably what happened here. I think Ed has had some reservations about this PR. Let me re-open it and we can discuss more.

**Comment by pponnuvel** [comment]
I've rebased and should be ready for a look @dosaboy 

@facundofc I no longer have the sosreport in which I first encountered this issue. Do you have a sosreport that you can share with us? You can share with us privately if it's sensitive. Thanks.

**Comment by pponnuvel** [comment]
This has been fixed in #1052 by doing the same change globally. Please test with the latest hotsos if anyone is facing this.

**Pull request closed without merging**
