### PR TITLE
Add manual workflow trigger

### PR DESCRIPTION
**Pull request by nicolasbock**
Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>

### CODE REVIEW

**Comment by dosaboy** [comment]
Any chance you can add some info to the commit about why you are adding this? As I understand it this allows you to run a workflow manually but since they are run on every push why would we need this?

**Comment by dosaboy** [comment]
It is possible to allow people to re-run workflows/jobs. I am able to do this already but that may not be the case for all users but I can take a look if it can be enabled. Presumably if that is possible this would not be needed?

**Comment by nicolasbock** [comment]
Interesting, I was assuming that since I can't re-run jobs it's because this trigger is missing. But maybe that's not the problem after all.

**Comment by nicolasbock** [comment]
The reason I was even looking at this was because for some reason CI didn't run for the last change set of canonical/hotsos#491 . I wanted to trigger a run but couldn't.

**Comment by dosaboy** [comment]
Ok i found the answer - https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs - so ill land this patch and we'll see how it goes.

**Pull request merged**
